main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.story1,name='home'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('lainnya', views.lainnya, name='lainnya'),
    path('story1', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def story1(request):
    return render(request,'story1.html')

project_name/views.py
from django.shortcuts import render


def home(request):
    return render(request,'index.html')
def lainnya(request):
    return render(request,'lainnya.html')

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container-tiga">
    <div class="twitter">
        <table>
            <tr>
                <td><img src="{% static 'pngegg.png' %}" width="30px" height="30px"></td>
                <td>jafar</td>
            </tr>
        </table>
    </div>
    <div class="instagram">
        <table>
            <tr>
                <td><img src="{% static 'instagram.png' %}" width="30px" height="30px"></td>
                <td>jafar</td>
            </tr>
        </table>
    </div>
    <div class="email">
        <table>
            <tr>
                <td><img src="{% static 'email.png' %}" width="30px" height="30px"></td>
                <td>jafar@gmail.com</td>
            </tr>
        </table>
    </div>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% include "navbar.html" %}
<div class="container-satu">
    <div class="sidebar">
        <div class="foto">
            <img src="{% static 'circle-cropped.png' %}" width="120" height="130">
        </div>
        <div class="biodata">
            <table>
                <tr>
                    <td>Nama</td>
                    <td>Jafar Abdurrohman</td>
                </tr>

                <tr>
                    <td>NPM</td>
                    <td>1906350843</td>
                </tr>

                <tr>
                    <td>Angkatan</td>
                    <td>2019</td>
                </tr>

                <tr>
                    <td>Hobi</td>
                    <td>Membaca</td>
                </tr>

                <tr>
                    <td>Kuliah</td>
                    <td>Fasilkom UI</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="isi">
        <div class="deskripsi">
            <h2>About me</h2>
            <p>Anak ke 3 di keluarga dengan 5 orang anak. sejak kecil suka berolahraga dan menaruh minat di bidang IT.</p>
        </div>
        <div class="pendidikan">
            <h2>Riwayat Pendidikan</h2>
            <table>
                <tr>
                    <td>2005-2007</td>
                    <td>TK Bahrul ulum</td>
                </tr>

                <tr>
                    <td>2007-2013</td>
                    <td>SD Negeri Puspiptek</td>
                </tr>

                <tr>
                    <td>2013-2016</td>
                    <td>SMPIT Insan Harapan</td>
                </tr>

                <tr>
                    <td>2016-2019</td>
                    <td>SMA Negeri 2 Tangerang Selatan</td>
                </tr>

                <tr>
                    <td>2019-Sekarang</td>
                    <td>Universitas Indonesia</td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>

templates/lainnya.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Quotes</title>
</head>
<body>
{% include "navbar.html" %}
<div class="container-utama">
    <div class="isi2">
        <div class="quotes">
            <p>
                "Imajinasi lebih penting daripada pengetahuan.
                Hanya ada dua hal yang tak terbatas. Alam semesta dan kebodohan manusia, dan aku tidak yakin yang pertama benar.
                Hidup itu seperti naik sepeda. Untuk menjaga keseimbangan Anda, Anda harus terus bergerak.
                Imajinasi adalah segalanya; imajinasi merupakan gambaran awal daya tarik kehidupan mendatang.
                Lihatlah alam dengan seksama, maka kamu akan mengerti segalanya dengan lebih baik.
                Aku tidak memiliki bakat khusus, aku hanya punya rasa penasaran yang besar.
                Di tengah kesulitan terdapat kesempatan.
                Jika Anda tidak dapat menjelaskan sesuatu hal secara sederhana, itu artinya Anda belum cukup paham.
                Hal yang penting adalah tidak berhenti bertanya. Keingintahuan memiliki alasan kenapa ada.
                Kegilaan: melakukan hal yang sama terus menerus dan mengharapkan hasil yang berbeda." Albert Einstein
            </p>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav>
    <div class="logo">
        <h3>Jafar Abdurrohman</h3>
    </div>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'lainnya' %}">Lainnya</a></li>
        <li><a href="{% url 'main:home' %}">Story1</a></li>
    </ul>
</nav>
</body>
</html>

templates/story1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Story 1</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% include "navbar.html" %}
<div>
    <img src="{% static '16393.jpg' %}" width='150' height='200'>
</div>

<div >
    <h2>Biodata</h2>
    <table>
        <tr>
            <td>Nama</td>
            <td>Jafar Abdurrohman</td>
        </tr>

        <tr>
            <td>NPM</td>
            <td>1906350843</td>
        </tr>

        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>

        <tr>
            <td>Hobi</td>
            <td>Membaca</td>
        </tr>

        <tr>
            <td>Kuliah</td>
            <td>Fasilkom UI</td>
        </tr>
    </table>
</div>

<div>
    <h2>Deskripsi tentang saya</h2>
    <p>Anak ke 3 di keluarga dengan 5 orang anak. sejak kecil suka berolahraga dan menaruh minat di bidang IT.</p>
</div>

<div>
    <h2>Riwayat Pendidikan</h2>
    <table>
        <tr>
            <td>2005-2007</td>
            <td>TK Bahrul ulum</td>
        </tr>

        <tr>
            <td>2007-2013</td>
            <td>SD Negeri Puspiptek</td>
        </tr>

        <tr>
            <td>2013-2016</td>
            <td>SMPIT Insan Harapan</td>
        </tr>

        <tr>
            <td>2016-2019</td>
            <td>SMA Negeri 2 Tangerang Selatan</td>
        </tr>

        <tr>
            <td>2019-Sekarang</td>
            <td>Universitas Indonesia</td>
        </tr>
    </table>
    <div>
        <h2>Media Sosial</h2>
        <table>
            <tr>
                <td>Twitter</td>
                <td>sroop_</td>
            </tr>

            <tr>
                <td>Instagram</td>
                <td>jafarabdurrohman</td>
            </tr>
        </table>

</div>
</body>
</html>